# Generated by Django 4.2.7 on 2026-06-21 12:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_number', models.CharField(blank=True, db_index=True, help_text='Auto-assigned, e.g. INW/2026/0001 (unique per company).', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('count_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory count',
                'verbose_name_plural': 'Inventory counts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_name', models.CharField(blank=True, help_text='Snapshot of product name at time of count creation.', max_length=255)),
                ('product_unit', models.CharField(blank=True, help_text='Snapshot of product unit at time of count creation.', max_length=20)),
                ('quantity_system', models.DecimalField(decimal_places=3, help_text='Stock quantity at time of count creation (system value).', max_digits=10)),
                ('quantity_actual', models.DecimalField(blank=True, decimal_places=3, help_text='Physically counted quantity (filled by user).', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.inventorycount')),
            ],
            options={
                'verbose_name': 'Inventory count item',
                'verbose_name_plural': 'Inventory count items',
                'ordering': ['product__name'],
            },
        ),
    ]
