# Generated by Django 4.2.7 on 2026-06-21 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('inventory', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_counts', to='users.company'),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_counts_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorycount',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_counts', to='products.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='inventorycount',
            constraint=models.UniqueConstraint(fields=('company', 'document_number'), name='inventory_count_company_document_number_uniq'),
        ),
    ]
