# Generated by Django 4.2.7 on 2026-06-21 12:29

from decimal import Decimal
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_number', models.CharField(blank=True, max_length=32)),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('simple', 'Tryb prosty (z receptury)'), ('batch', 'Tryb wsadu (realne zużycie)')], default='simple', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('completed', 'Zakończone')], default='draft', max_length=20)),
                ('quantity_produced', models.DecimalField(decimal_places=2, help_text='Actual finished units produced.', max_digits=10)),
                ('total_input_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('real_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity_used', models.DecimalField(decimal_places=4, help_text='Actual quantity consumed (includes waste).', max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('fifo_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
            ],
            options={
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, help_text='Optional display name override.', max_length=255)),
                ('yield_quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='How many units one full recipe produces (e.g. 100 kartaczy).', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity per recipe.yield_quantity units of finished good.', max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['ingredient__name'],
            },
        ),
    ]
