# Generated by Django 4.2.7 on 2026-06-12 19:44

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0012_pz_kor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_product_avg_cost'),
        ('users', '0009_track_supplier_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, max_length=32)),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('simple', 'Tryb prosty (z receptury)'), ('batch', 'Tryb wsadu (realne zużycie)')], default='simple', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('completed', 'Zakończone')], default='draft', max_length=20)),
                ('quantity_produced', models.DecimalField(decimal_places=2, help_text='Actual finished units produced.', max_digits=10)),
                ('total_input_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('real_unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='users.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders_created', to=settings.AUTH_USER_MODEL)),
                ('pw_document', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order_pw', to='delivery.deliverydocument')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='Optional display name override.', max_length=255)),
                ('yield_quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='How many units one full recipe produces (e.g. 100 kartaczy).', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='users.company')),
                ('product', models.ForeignKey(help_text='The finished good this recipe produces.', on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='products.product')),
            ],
            options={
                'ordering': ['product__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrderInput',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_used', models.DecimalField(decimal_places=4, help_text='Actual quantity consumed (includes waste).', max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('fifo_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_inputs', to='products.product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='production.productionorder')),
            ],
            options={
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.AddField(
            model_name='productionorder',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.recipe'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='rw_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order_rw', to='delivery.deliverydocument'),
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity per recipe.yield_quantity units of finished good.', max_digits=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_uses', to='products.product')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.recipe')),
            ],
            options={
                'ordering': ['ingredient__name'],
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['company'], name='idx_recipe_company'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['product'], name='idx_recipe_product'),
        ),
        migrations.AlterUniqueTogether(
            name='productionorderinput',
            unique_together={('order', 'ingredient')},
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['company'], name='idx_prodorder_company'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['date'], name='idx_prodorder_date'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status'], name='idx_prodorder_status'),
        ),
    ]
