# Generated by Django 4.2.7 on 2026-06-21 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0002_initial'),
        ('products', '0001_initial'),
        ('delivery', '0004_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='users.company'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='product',
            field=models.ForeignKey(help_text='The finished good this recipe produces.', on_delete=django.db.models.deletion.PROTECT, related_name='recipes', to='products.product'),
        ),
        migrations.AddField(
            model_name='productionorderinput',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_inputs', to='products.product'),
        ),
        migrations.AddField(
            model_name='productionorderinput',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='production.productionorder'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='users.company'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='pw_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order_pw', to='delivery.deliverydocument'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='production.recipe'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='rw_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_order_rw', to='delivery.deliverydocument'),
        ),
        migrations.AlterUniqueTogether(
            name='recipeitem',
            unique_together={('recipe', 'ingredient')},
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['company'], name='idx_recipe_company'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['product'], name='idx_recipe_product'),
        ),
        migrations.AlterUniqueTogether(
            name='productionorderinput',
            unique_together={('order', 'ingredient')},
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['company'], name='idx_prodorder_company'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['date'], name='idx_prodorder_date'),
        ),
        migrations.AddIndex(
            model_name='productionorder',
            index=models.Index(fields=['status'], name='idx_prodorder_status'),
        ),
    ]
