# Generated by Django 4.2.1 on 2026-04-20 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional product description', null=True)),
                ('unit', models.CharField(help_text="Unit of measurement (e.g., 'szt', 'kg', 'l')", max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Product price', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current stock quantity', validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(blank=True, help_text='Optional product category', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'unit')},
            },
        ),
    ]
