# Generated by Django 4.2.7 on 2026-04-23 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_company_and_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('products', 'Products & Inventory'), ('customers', 'Customers'), ('warehouses', 'Warehouse Management'), ('orders', 'Orders'), ('delivery', 'Delivery & WZ Documents'), ('invoicing', 'Invoicing'), ('ksef', 'KSeF Integration'), ('reporting', 'Reporting & Analytics')], max_length=50)),
                ('is_enabled', models.BooleanField(default=False)),
                ('enabled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='users.company')),
            ],
            options={
                'unique_together': {('company', 'module')},
            },
        ),
    ]
