# Generated by Django 4.2.7 on 2026-04-23 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_company_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.company'),
        ),
    ]
