# Generated by Django 4.2.7 on 2026-05-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ksef_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodule',
            name='module',
            field=models.CharField(choices=[('products', 'Products & Inventory'), ('customers', 'Customers'), ('warehouses', 'Warehouse Management'), ('orders', 'Orders'), ('delivery', 'Delivery & WZ/ZW Documents'), ('invoicing', 'Invoicing'), ('van_routes', 'Van Routes & Mobile Delivery'), ('purchasing', 'Purchasing & Suppliers (PZ)'), ('production', 'Own Production (PW/RW)'), ('ksef', 'KSeF Integration'), ('reporting', 'Reporting & Analytics')], max_length=50),
        ),
    ]
