# Generated by Django 4.2.7 on 2026-06-04 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_van_routes_purchasing_production_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWorkflowSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orders_required', models.BooleanField(default=False, help_text='If True, WZ documents must reference an Order. Standalone WZ creation is blocked at the API level.')),
                ('wz_required_before_invoice', models.BooleanField(default=True, help_text='If True, at least one delivered WZ must exist before an invoice can be issued for an order. Disable for service companies that invoice directly from the order without physical delivery.')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_settings', to='users.company')),
            ],
            options={
                'verbose_name': 'Company workflow settings',
                'verbose_name_plural': 'Company workflow settings',
            },
        ),
    ]
