# Generated by Django 4.2.7 on 2026-06-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_fcm_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, choices=[('invoicing', 'Tylko fakturowanie'), ('van_selling', 'Van Selling'), ('warehouse', 'Magazyn i handel'), ('production', 'Produkcja'), ('mixed', 'Mieszany')], default='invoicing', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companymodule',
            name='module',
            field=models.CharField(choices=[('products', 'Products & Inventory'), ('customers', 'Customers'), ('warehouses', 'Warehouse Management'), ('orders', 'Orders'), ('delivery', 'Delivery & WZ/ZW Documents'), ('invoicing', 'Invoicing'), ('van_routes', 'Van Routes & Mobile Delivery'), ('purchasing', 'Purchasing & Suppliers (PZ)'), ('production', 'Own Production (PW/RW)'), ('ksef_inbox', 'KSeF Inbox (Received Invoices)'), ('ksef', 'KSeF Integration'), ('reporting', 'Reporting & Analytics'), ('cost_allocation', 'Cost Allocation & Accounting Notes')], max_length=50),
        ),
    ]
