# Generated by Django 4.2.7 on 2026-06-24 12:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_add_web_push_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('is_admin', models.BooleanField(default=False)),
                ('can_manage_team', models.BooleanField(default=False, help_text='Zarządzanie pracownikami i rolami')),
                ('can_manage_settings', models.BooleanField(default=False, help_text='Ustawienia firmy, moduły, przepływ dokumentów')),
                ('can_see_prices', models.BooleanField(default=True, help_text='Widoczność cen i kwot we wszystkich dokumentach')),
                ('can_manage_products', models.BooleanField(default=False, help_text='Produkty, stany magazynowe')),
                ('can_manage_customers', models.BooleanField(default=False, help_text='Klienci')),
                ('can_manage_orders', models.BooleanField(default=False, help_text='Zamówienia')),
                ('can_manage_delivery', models.BooleanField(default=False, help_text='Dokumenty WZ/ZW, dostawa')),
                ('can_access_routes', models.BooleanField(default=False, help_text='Trasy vana')),
                ('can_manage_invoices', models.BooleanField(default=False, help_text='Faktury')),
                ('can_manage_purchasing', models.BooleanField(default=False, help_text='Zakupy, dostawcy, dokumenty PZ')),
                ('can_manage_production', models.BooleanField(default=False, help_text='Produkcja, receptury')),
                ('can_view_reports', models.BooleanField(default=False, help_text='Raporty i analizy')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='users.company')),
            ],
            options={
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AddField(
            model_name='companymembership',
            name='company_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.companyrole'),
        ),
    ]
