# Generated by Django 4.2.7 on 2026-07-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_company_taxation_form_ryczalt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodule',
            name='module',
            field=models.CharField(choices=[('products', 'Products & Inventory'), ('customers', 'Customers'), ('warehouses', 'Warehouse Management'), ('orders', 'Orders'), ('delivery', 'Delivery & WZ/ZW Documents'), ('invoicing', 'Invoicing'), ('van_routes', 'Van Routes & Mobile Delivery'), ('purchasing', 'Purchasing & Suppliers (PZ)'), ('production', 'Own Production (PW/RW)'), ('ksef_inbox', 'KSeF Inbox (Received Invoices)'), ('ksef', 'KSeF Integration'), ('reporting', 'Reporting & Analytics'), ('cost_allocation', 'Cost Allocation & Accounting Notes'), ('fixed_costs', 'Fixed Costs & Personnel')], max_length=50),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='can_manage_accounting',
            field=models.BooleanField(default=False, help_text='Adnotacje kosztowe — opisywanie faktur i projekty kosztowe'),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='can_manage_inventory',
            field=models.BooleanField(default=False, help_text='Inwentaryzacja — dokumenty INW'),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='can_manage_products',
            field=models.BooleanField(default=False, help_text='Produkty — katalog produktów i ceny'),
        ),
        migrations.AlterField(
            model_name='companyrole',
            name='can_manage_warehouses',
            field=models.BooleanField(default=False, help_text='Magazyny — zarządzanie magazynami'),
        ),
    ]
