# Generated by Django 4.2.7 on 2026-07-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_companymodule_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bank_account_iban',
            field=models.CharField(blank=True, default='', help_text='IBAN rachunku bankowego (prefill na fakturach, np. PL12345678901234567890123456).', max_length=34),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text='Nazwa banku (opcjonalnie, wyświetlana na fakturze).', max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_swift',
            field=models.CharField(blank=True, default='', help_text='Kod SWIFT/BIC banku (opcjonalnie).', max_length=11),
        ),
        migrations.AddField(
            model_name='company',
            name='bdo',
            field=models.CharField(blank=True, default='', help_text='Numer BDO (rejestr odpadów).', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='krs',
            field=models.CharField(blank=True, default='', help_text='Numer KRS (10 cyfr).', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='regon',
            field=models.CharField(blank=True, default='', help_text='Numer REGON (9 lub 14 cyfr).', max_length=14),
        ),
    ]
