# Generated by Django 4.2.7 on 2026-08-29 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_ksef_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_vat_payer',
            field=models.BooleanField(default=False, help_text='Czy firma jest czynnym podatnikiem VAT.'),
        ),
    ]
