# Generated by Django 4.2.7 on 2026-09-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_company_ksef_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyrole',
            name='can_manage_purchase_orders',
            field=models.BooleanField(default=False, help_text='Zamówienia do dostawców (ZD)'),
        ),
        migrations.AlterField(
            model_name='companymodule',
            name='module',
            field=models.CharField(choices=[('products', 'Products & Inventory'), ('customers', 'Customers'), ('warehouses', 'Warehouse Management'), ('orders', 'Orders'), ('delivery', 'Delivery & WZ/ZW Documents'), ('invoicing', 'Invoicing'), ('van_routes', 'Van Routes & Mobile Delivery'), ('purchasing', 'Purchasing & Suppliers (PZ)'), ('purchase_orders', 'Purchase Orders — ZD'), ('production', 'Own Production (PW/RW)'), ('ksef_inbox', 'KSeF Inbox (Received Invoices)'), ('ksef', 'KSeF Integration'), ('reporting', 'Reporting & Analytics'), ('cost_allocation', 'Cost Allocation & Accounting Notes'), ('fixed_costs', 'Fixed Costs & Personnel')], max_length=50),
        ),
    ]
