# Generated by Django 4.2.7 on 2026-09-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_company_invoice_returns_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price_input_mode',
            field=models.CharField(choices=[('net', 'Ceny netto (standard B2B)'), ('gross', 'Ceny brutto (retail / detaliczne)')], default='net', help_text='Czy firma wprowadza ceny netto czy brutto. Wpływa na obliczenia na fakturach i zamówieniach.', max_length=5),
        ),
    ]
