# Generated by Django 4.2.7 on 2026-09-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_company_price_input_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_number_prefix',
            field=models.CharField(default='FV', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_number_period',
            field=models.CharField(
                choices=[('yearly', 'Roczna'), ('monthly', 'Miesięczna')],
                default='yearly',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_number_padding',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='company',
            name='invoice_number_start',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
