# Generated by Django 4.2.7 on 2026-08-01 19:16

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0021_ksef_optional_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('fuel', 'Paliwo'), ('raw_materials', 'Surowce / materiały'), ('transport', 'Transport / dostawa'), ('repair', 'Naprawa / awaria'), ('packaging', 'Opakowania'), ('utilities', 'Media / rachunki'), ('other', 'Inne')], default='other', max_length=20)),
                ('cost_type', models.CharField(choices=[('direct', 'Koszt bezpośredni (wpływa na marżę produktu)'), ('indirect', 'Koszt ogólny (wpływa na cash flow)')], default='indirect', max_length=10)),
                ('has_vat', models.BooleanField(default=False, help_text='Czy ten wydatek ma fakturę VAT do odliczenia?')),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_expenses', to='users.company')),
            ],
            options={
                'verbose_name': 'Quick Expense',
                'verbose_name_plural': 'Quick Expenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyB2CRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, help_text='Kwota brutto (zawiera VAT, jeśli vat_included=True).', max_digits=12)),
                ('vat_included', models.BooleanField(default=True, help_text='Czy kwota zawiera VAT?')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('23.00'), help_text='Stawka VAT w % (np. 23.00).', max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2c_revenues', to='users.company')),
            ],
            options={
                'verbose_name': 'Daily B2C Revenue',
                'verbose_name_plural': 'Daily B2C Revenues',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTaxConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tax_form', models.CharField(choices=[('kpir_linear', 'KPiR – podatek liniowy 19%'), ('kpir_scale', 'KPiR – skala podatkowa'), ('ryczalt', 'Ryczałt od przychodów')], default='kpir_linear', max_length=20)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('19.00'), help_text='Stawka podatku dochodowego w % (np. 19.00 dla KPiR liniowego).', max_digits=5)),
                ('vat_payer', models.BooleanField(default=True, help_text='Czy firma jest płatnikiem VAT?')),
                ('vat_method', models.CharField(choices=[('memoriałowa', 'Memoriałowa (od daty faktury)'), ('kasowa', 'Kasowa (od daty zapłaty)')], default='memoriałowa', max_length=20)),
                ('vat_due_day', models.IntegerField(default=25, help_text='Dzień miesiąca, do którego należy zapłacić VAT (domyślnie 25).')),
                ('zus_due_day', models.IntegerField(default=20, help_text='Dzień miesiąca, do którego należy zapłacić ZUS (domyślnie 20).')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gotówka w kasie/kasetce (wpisana ręcznie).', max_digits=14)),
                ('bank_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stan konta bankowego (wpisany ręcznie).', max_digits=14)),
                ('balance_updated_at', models.DateTimeField(blank=True, help_text='Kiedy ostatnio zaktualizowano salda.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_config', to='users.company')),
            ],
            options={
                'verbose_name': 'Company Tax Config',
                'verbose_name_plural': 'Company Tax Configs',
            },
        ),
    ]
