# Generated by Django 4.2.7 on 2026-08-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickexpense',
            name='document_type',
            field=models.CharField(choices=[('paragon', 'Paragon'), ('faktura_vat', 'Faktura VAT'), ('wz', 'WZ / dokument magazynowy'), ('inne', 'Inny dokument')], default='paragon', max_length=20),
        ),
        migrations.AddField(
            model_name='quickexpense',
            name='product_name',
            field=models.CharField(blank=True, help_text='Optional product description (from product catalog or free text)', max_length=255),
        ),
        migrations.AlterField(
            model_name='quickexpense',
            name='category',
            field=models.CharField(choices=[('raw_materials', 'Surowce / materiały'), ('packaging', 'Opakowania'), ('fuel', 'Paliwo'), ('transport', 'Transport / dostawa'), ('utilities', 'Media / rachunki'), ('rent', 'Czynsz / leasing'), ('services', 'Usługi zewnętrzne'), ('marketing', 'Marketing / reklama'), ('salaries', 'Wynagrodzenia'), ('repair', 'Naprawa / serwis'), ('other', 'Inne')], default='other', max_length=20),
        ),
    ]
