# Generated by Django 4.2.7 on 2026-08-02 14:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_ksef_optional_fields'),
        ('cash_flow', '0002_quickexpense_document_type_quickexpense_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOpexCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(blank=True, help_text="Machine-readable key, e.g. 'raw_materials'. Used to match legacy hardcoded categories.", max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opex_categories', to='users.company')),
            ],
            options={
                'verbose_name': 'Company OPEX Category',
                'verbose_name_plural': 'Company OPEX Categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('company', 'slug')},
            },
        ),
    ]
