# Generated by Django 4.2.7 on 2026-08-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0003_companyopexcategory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyopexcategory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='companyopexcategory',
            constraint=models.UniqueConstraint(condition=models.Q(('slug__gt', '')), fields=('company', 'slug'), name='unique_company_slug_nonempty'),
        ),
    ]
