# Generated by Django 4.2.7 on 2026-08-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0004_opex_category_unique_nonempty_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytaxconfig',
            name='has_sick_insurance',
            field=models.BooleanField(default=False, help_text='Czy opłaca dobrowolną składkę chorobową (2,45%)?'),
        ),
        migrations.AddField(
            model_name='companytaxconfig',
            name='zus_status',
            field=models.CharField(choices=[('ulga_na_start', 'Ulga na start (bez składek społ.)'), ('preferencyjny', 'Preferencyjny ZUS'), ('maly_zus_plus', 'Mały ZUS Plus (kwota zmienna)'), ('pelny_zus', 'Pełny ZUS'), ('etat_plus_jdg', 'Etat + JDG (etat ≥ min. wynagrodzenie)')], default='pelny_zus', help_text='Status ZUS przedsiębiorcy.', max_length=20),
        ),
    ]
