# Generated by Django 4.2.7 on 2026-08-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0005_add_zus_status_and_sick_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickexpense',
            name='document_type',
            field=models.CharField(choices=[('paragon', 'Paragon'), ('faktura_vat', 'Faktura VAT'), ('faktura_pdf', 'Faktura PDF'), ('faktura_rr', 'Faktura RR (rolnicza)'), ('wz', 'WZ / dokument magazynowy'), ('inne', 'Inny dokument')], default='paragon', max_length=20),
        ),
    ]
