# Generated by Django 4.2.7 on 2026-08-08 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0006_add_document_type_pdf_rr'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickexpense',
            name='amount_net',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kwota netto — wypełniana gdy dokument ma VAT do odliczenia.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='quickexpense',
            name='vat_rate',
            field=models.CharField(blank=True, default='', help_text='Stawka VAT: 23, 8, 5, 0 (pusty = nie dotyczy).', max_length=5),
        ),
    ]
