# Generated by Django 4.2.7 on 2026-08-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0007_add_amount_net_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickexpense',
            name='lines',
            field=models.JSONField(blank=True, default=list, help_text='Line items: [{name, quantity, unit, unit_price, vat_rate, line_net, line_gross}]. When present, amount/amount_net are derived from line totals.'),
        ),
    ]
