# Generated by Django 4.2.7 on 2026-08-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0008_add_lines_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyb2crevenue',
            name='cost_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Suma kosztów własnych ze sprzedaży (qty × avg_cost). Tylko dla sale_type='products'.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyb2crevenue',
            name='lines',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot linii sprzedaży: [{product_id, name, qty, unit_price, unit_cost, line_revenue, line_cost}]'),
        ),
        migrations.AddField(
            model_name='dailyb2crevenue',
            name='sale_type',
            field=models.CharField(default='manual', help_text="'manual' = kwota z kasy, 'products' = wpisane produkty", max_length=20),
        ),
    ]
