# Generated by Django 4.2.7 on 2026-08-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0009_add_b2c_product_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytaxconfig',
            name='balance_date',
            field=models.DateField(blank=True, help_text='Na jaki dzień podano salda (kotwica harmonogramu).', null=True),
        ),
    ]
