# Generated by Django 4.2.7 on 2026-08-31 16:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0010_add_balance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companytaxconfig',
            name='vat_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stan rachunku VAT (środki zablokowane — mechanizm podzielonej płatności).', max_digits=14),
        ),
    ]
