# Generated by Django 4.2.7 on 2026-09-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_flow', '0011_add_vat_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickexpense',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Personal spend — no VAT deduction and not a business cost.'),
        ),
        migrations.AddField(
            model_name='quickexpense',
            name='vat_deduction',
            field=models.CharField(choices=[('full', '100% — działalność'), ('half', '50% — samochód osobowy'), ('none', '0% — brak odliczenia')], default='full', help_text='VAT input share: 100%, 50% passenger car, or 0%.', max_length=10),
        ),
    ]
