# Generated by Django 4.2.7 on 2026-04-23 11:14

from django.db import migrations, models
import django.db.models.deletion


def backfill_order_company(apps, schema_editor):
    Order = apps.get_model("orders", "Order")
    for row in Order.objects.all():
        if row.company_id:
            continue
        row.company_id = row.customer.company_id
        row.save(update_fields=["company_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_current_company"),
        ("customers", "0003_add_company_fk"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
        migrations.RunPython(backfill_order_company, migrations.RunPython.noop),
    ]
