# Generated by Django 4.2.7 on 2026-06-21 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderchangelog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderchangelog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='orders.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.company'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(help_text='Customer who placed the order', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created or last updated (audit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('company', 'order_number'), name='orders_order_company_order_number_uniq'),
        ),
    ]
