# Generated by Django 4.2.7 on 2026-04-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_uuid_and_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, help_text='Human-readable id, e.g. ZAM/2026/0001 (unique per company)', max_length=32, null=True),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('company', 'order_number'), name='orders_order_company_order_number_uniq'),
        ),
    ]
