# Generated by Django 4.2.7 on 2026-05-18 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0006_orderitem_pricing_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('change_type', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed'), ('qty_changed', 'Quantity changed'), ('price_changed', 'Price changed')], max_length=20)),
                ('product_id', models.UUIDField()),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('product_unit', models.CharField(blank=True, default='', max_length=20)),
                ('quantity_before', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price_gross_before', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price_gross_after', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='orders.order')),
            ],
            options={
                'verbose_name': 'Order Change Log',
                'verbose_name_plural': 'Order Change Logs',
                'ordering': ['-changed_at'],
            },
        ),
    ]
