# Generated by Django 4.2.7 on 2026-05-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('in_preparation', 'In preparation'), ('loaded', 'Loaded'), ('in_delivery', 'In delivery'), ('partially_delivered', 'Partially delivered'), ('delivered', 'Delivered'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='draft', help_text='Current status of the order', max_length=20),
        ),
    ]
