# Generated by Django 4.2.1 on 2026-04-20 10:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer or shop name', max_length=255)),
                ('address', models.TextField(help_text='Full address of the customer')),
                ('nip', models.CharField(blank=True, help_text='Tax identification number (NIP)', max_length=10, null=True, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('distance', models.IntegerField(help_text='Distance in kilometers', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['-created_at'],
                'unique_together': {('name', 'nip')},
            },
        ),
    ]
