# Generated by Django 4.2.7 on 2026-07-06 14:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0020_alter_companymodule_module_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('wynagrodzenia', 'Wynagrodzenia'), ('zus_zdrowotne', 'ZUS / Zdrowotne'), ('czynsz', 'Czynsz / Najem'), ('leasing', 'Leasing'), ('inne', 'Inne')], default='inne', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount_monthly', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active_from', models.DateField(help_text='Pierwszy miesiąc, od którego koszt obowiązuje (YYYY-MM-01).')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_costs', to='users.company')),
            ],
            options={
                'ordering': ['category', 'description'],
            },
        ),
    ]
