# Generated by Django 4.2.7 on 2026-07-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_costs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedcost',
            name='category',
            field=models.CharField(choices=[('wynagrodzenia', 'Wynagrodzenia'), ('zus_zdrowotne', 'ZUS / Zdrowotne'), ('czynsz', 'Czynsz / Najem'), ('leasing', 'Leasing / Raty'), ('ubezpieczenia', 'Ubezpieczenia'), ('ksiegowosc', 'Biuro rachunkowe'), ('subskrypcje', 'Subskrypcje i software'), ('paliwo', 'Paliwo'), ('inne', 'Inne')], default='inne', max_length=20),
        ),
    ]
