# Generated by Django 4.2.7 on 2026-08-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_costs', '0002_alter_fixedcost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedcost',
            name='due_day',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Dzień miesiąca, do którego należy opłacić (1–31). Puste = brak określonego terminu.', null=True),
        ),
    ]
