# Generated by Django 4.2.7 on 2026-06-21 12:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('document_type', models.CharField(choices=[('WZ', 'Wydanie Zewnętrzne'), ('MM', 'Przesunięcie Międzymagazynowe'), ('PZ', 'Przyjęcie Zewnętrzne'), ('ZW', 'Zwrot Zewnętrzny'), ('RW', 'Rozchód Wewnętrzny'), ('PZ-KOR', 'Korekta Przyjęcia Zewnętrznego')], max_length=6)),
                ('document_number', models.CharField(blank=True, help_text='Assigned on save, e.g. WZ/2026/0001 (unique per company).', max_length=32, null=True)),
                ('issue_date', models.DateField(help_text='Document issue date (year drives numbering).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('has_returns', models.BooleanField(default=False)),
                ('returns_notes', models.TextField(blank=True, default='')),
                ('driver_name', models.CharField(blank=True, default='', max_length=255)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=255)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('external_document_number', models.CharField(blank=True, default='', help_text='Nr dokumentu dostawcy (WZ/list przewozowy) — wypełniany ręcznie przy PZ.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery document',
                'verbose_name_plural': 'Delivery documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity_planned', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_returned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Cena zakupu netto per jednostka — wypełniana przy PZ.', max_digits=10, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Data ważności partii — przenoszona na StockBatch przy przyjęciu PZ.', null=True)),
                ('ksef_invoice_line_position', models.PositiveSmallIntegerField(blank=True, help_text='Position of the source line in the KSeF invoice (0-based).', null=True)),
                ('return_reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_damaged', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.deliverydocument')),
            ],
            options={
                'verbose_name': 'Delivery item',
                'verbose_name_plural': 'Delivery items',
                'ordering': ['created_at'],
            },
        ),
    ]
