# Generated by Django 4.2.7 on 2026-04-26 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_company_fk_required'),
        ('orders', '0006_orderitem_pricing_snapshot'),
        ('products', '0008_company_fk_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_ksef_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('WZ', 'Wydanie Zewnętrzne'), ('MM', 'Przesunięcie Międzymagazynowe'), ('PZ', 'Przyjęcie Zewnętrzne')], max_length=2)),
                ('document_number', models.CharField(blank=True, help_text='Assigned on save, e.g. WZ/2026/0001 (unique per company).', max_length=32, null=True)),
                ('issue_date', models.DateField(help_text='Document issue date (year drives numbering).')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('saved', 'Saved'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('has_returns', models.BooleanField(default=False)),
                ('returns_notes', models.TextField(blank=True, default='')),
                ('driver_name', models.CharField(blank=True, default='', max_length=255)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=255)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_documents', to='users.company')),
                ('from_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_documents_from', to='products.warehouse')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_documents', to='orders.order')),
                ('to_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_documents', to='customers.customer')),
                ('to_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_documents_to', to='products.warehouse')),
                ('user', models.ForeignKey(blank=True, help_text='User who created or last updated (audit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery document',
                'verbose_name_plural': 'Delivery documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='deliverydocument',
            constraint=models.UniqueConstraint(fields=('company', 'document_number'), name='delivery_document_company_document_number_uniq'),
        ),
    ]
