# Generated by Django 4.2.7 on 2026-04-26 15:00

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_pricing_snapshot'),
        ('products', '0008_company_fk_required'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_planned', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_returned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('return_reason', models.CharField(blank=True, default='', max_length=255)),
                ('is_damaged', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.deliverydocument')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Delivery item',
                'verbose_name_plural': 'Delivery items',
                'ordering': ['created_at'],
            },
        ),
    ]
