# Generated by Django 4.2.7 on 2026-06-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('delivery', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_items', to='products.product'),
        ),
    ]
