# Generated by Django 4.2.7 on 2026-06-21 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('van_routes', '0001_initial'),
        ('customers', '0002_initial'),
        ('ksef', '0001_initial'),
        ('users', '0001_initial'),
        ('delivery', '0003_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydocument',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_documents', to='users.company'),
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='corrects_pz',
            field=models.ForeignKey(blank=True, help_text='For PZ-KOR: the original PZ this document corrects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='delivery.deliverydocument'),
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='from_supplier',
            field=models.ForeignKey(blank=True, help_text='Dostawca — wypełniany dla dokumentów PZ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_documents', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='from_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_documents_from', to='products.warehouse'),
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='ksef_invoice',
            field=models.ForeignKey(blank=True, help_text='KSeF invoice this PZ was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pz_documents', to='ksef.receivedksefinvoice'),
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='linked_wz',
            field=models.ForeignKey(blank=True, help_text='For ZW documents: the WZ that triggered this return.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_documents', to='delivery.deliverydocument'),
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_documents', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='to_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_documents', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_documents_to', to='products.warehouse'),
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created or last updated (audit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliverydocument',
            name='van_route',
            field=models.ForeignKey(blank=True, help_text='Van route (trip) this document belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_documents', to='van_routes.vanroute'),
        ),
        migrations.AddConstraint(
            model_name='deliverydocument',
            constraint=models.UniqueConstraint(fields=('company', 'document_number'), name='delivery_document_company_document_number_uniq'),
        ),
    ]
