# Generated by Django 4.2.7 on 2026-05-29 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('delivery', '0004_add_zw_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydocument',
            name='from_supplier',
            field=models.ForeignKey(blank=True, help_text='Dostawca — wypełniany dla dokumentów PZ.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_documents', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='deliveryitem',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Cena zakupu netto per jednostka — wypełniana przy PZ.', max_digits=10, null=True),
        ),
    ]
