# Generated by Django 4.2.7 on 2026-06-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0012_pz_kor'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryitem',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Data ważności partii — przenoszona na StockBatch przy przyjęciu PZ.', null=True),
        ),
    ]
