# Generated by Django 4.2.7 on 2026-06-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydocument',
            name='corrects_wz',
            field=models.ForeignKey(blank=True, help_text='For WZ-KOR: the original WZ this document corrects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wz_corrections', to='delivery.deliverydocument'),
        ),
        migrations.AlterField(
            model_name='deliverydocument',
            name='corrects_pz',
            field=models.ForeignKey(blank=True, help_text='For PZ-KOR: the original PZ this document corrects.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pz_corrections', to='delivery.deliverydocument'),
        ),
        migrations.AlterField(
            model_name='deliverydocument',
            name='document_type',
            field=models.CharField(choices=[('WZ', 'Wydanie Zewnętrzne'), ('MM', 'Przesunięcie Międzymagazynowe'), ('PZ', 'Przyjęcie Zewnętrzne'), ('ZW', 'Zwrot Zewnętrzny'), ('RW', 'Rozchód Wewnętrzny'), ('PZ-KOR', 'Korekta Przyjęcia Zewnętrznego'), ('WZ-KOR', 'Korekta Wydania Zewnętrznego')], max_length=6),
        ),
    ]
