# Generated by Django 4.2.7 on 2026-09-07 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksef', '0012_alter_receivedksefinvoice_opex_category'),
        ('delivery', '0015_deliveryitem_batch_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverydocument',
            name='ksef_invoice',
            field=models.ForeignKey(blank=True, help_text='[LEGACY] KSeF invoice this PZ was created from — superseded by M:M ksef_links.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pz_documents', to='ksef.receivedksefinvoice'),
        ),
        migrations.CreateModel(
            name='DeliveryDocumentKSeFLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksef_links', to='delivery.deliverydocument')),
                ('ksef_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pz_ksef_links', to='ksef.receivedksefinvoice')),
            ],
            options={
                'verbose_name': 'Powiązanie PZ–KSeF',
                'verbose_name_plural': 'Powiązania PZ–KSeF',
                'ordering': ['linked_at'],
                'unique_together': {('delivery_document', 'ksef_invoice')},
            },
        ),
    ]
