# Generated by Django 4.2.7 on 2026-09-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_add_purchase_orders_module'),
        ('delivery', '0017_migrate_ksef_links_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydocument',
            name='source_supplier_order',
            field=models.ForeignKey(blank=True, help_text='ZD (SupplierOrder) this PZ was created from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pz_documents', to='purchase_orders.supplierorder'),
        ),
    ]
