# Generated by Django 4.2.7 on 2026-06-21 12:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cost project',
                'verbose_name_plural': 'Cost projects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('accounting_status', models.CharField(choices=[('pending', 'Do opisania'), ('annotated', 'Opisana'), ('exported', 'Wyeksportowana'), ('booked', 'Zaksięgowana')], default='pending', max_length=20)),
                ('accounting_notes', models.TextField(blank=True)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice annotation',
                'verbose_name_plural': 'Invoice annotations',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_private', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice line annotation',
                'verbose_name_plural': 'Invoice line annotations',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineAnnotationSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=100, help_text='Share of this line allocated to this project (0–100).', max_digits=6)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, help_text='Actual quantity allocated (when split was entered by items, not %).', max_digits=14, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line_annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='cost_allocation.invoicelineannotation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_splits', to='cost_allocation.costproject')),
            ],
            options={
                'verbose_name': 'Invoice line annotation split',
                'verbose_name_plural': 'Invoice line annotation splits',
                'ordering': ['created_at'],
            },
        ),
    ]
