# Generated by Django 4.2.7 on 2026-06-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ksef', '0001_initial'),
        ('cost_allocation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineannotation',
            name='line',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='ksef.receivedksefinvoiceline'),
        ),
        migrations.AddField(
            model_name='invoicelineannotation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_annotations', to='cost_allocation.costproject'),
        ),
        migrations.AddField(
            model_name='invoiceannotation',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', to='ksef.receivedksefinvoice'),
        ),
    ]
