# Generated by Django 4.2.7 on 2026-06-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_companymodule_module'),
        ('cost_allocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='costproject',
            name='unique_cost_project_per_company',
        ),
        migrations.AlterUniqueTogether(
            name='costproject',
            unique_together={('company', 'name')},
        ),
    ]
