# Generated by Django 4.2.1 on 2026-06-11 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cost_allocation', '0002_remove_costproject_unique_cost_project_per_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineAnnotationSplit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=2, default=100, help_text='Share of this line allocated to this project (0–100).', max_digits=6)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('line_annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='cost_allocation.invoicelineannotation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_splits', to='cost_allocation.costproject')),
            ],
            options={
                'verbose_name': 'Invoice line annotation split',
                'verbose_name_plural': 'Invoice line annotation splits',
                'ordering': ['created_at'],
            },
        ),
    ]
