# Generated by Django 4.2.1 on 2026-06-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_allocation', '0003_add_invoice_line_annotation_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineannotationsplit',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Actual quantity allocated (when split was entered by items, not %).', max_digits=14, null=True),
        ),
    ]
