# Generated by Django 4.2.7 on 2026-08-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_allocation', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineannotation',
            name='opex_category',
            field=models.CharField(blank=True, choices=[('raw_materials', 'Surowce / materiały'), ('packaging', 'Opakowania'), ('fuel', 'Paliwo'), ('transport', 'Transport / dostawa'), ('utilities', 'Media / rachunki'), ('rent', 'Czynsz / leasing'), ('services', 'Usługi zewnętrzne'), ('marketing', 'Marketing / reklama'), ('salaries', 'Wynagrodzenia'), ('repair', 'Naprawa / serwis'), ('other', 'Inne')], help_text='Cost category for this line item — used in cash flow calculations.', max_length=20, null=True),
        ),
    ]
