# Generated by Django 4.2.7 on 2026-09-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocument',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Czy dokument został opłacony. Paragony domyślnie True (płatność przy kasie).'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='opex_category',
            field=models.CharField(blank=True, help_text="Slug kategorii kosztu OPEX (np. 'raw_materials', kategoria niestandardowa).", max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Data i godzina oznaczenia jako opłacone.', null=True),
        ),
    ]
