# Generated by Django 4.2.7 on 2026-09-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0015_deliveryitem_batch_number'),
        ('purchase_documents', '0004_purchasedocument_line_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedocument',
            name='delivery_document',
            field=models.ForeignKey(blank=True, help_text='[LEGACY] PZ powiązane z tym dokumentem zakupowym — zastąpione przez M:M pz_links.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_documents', to='delivery.deliverydocument'),
        ),
        migrations.CreateModel(
            name='PurchaseDocumentPzLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_doc_links', to='delivery.deliverydocument')),
                ('purchase_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pz_links', to='purchase_documents.purchasedocument')),
            ],
            options={
                'verbose_name': 'Powiązanie Faktura–PZ',
                'verbose_name_plural': 'Powiązania Faktura–PZ',
                'ordering': ['linked_at'],
                'unique_together': {('purchase_document', 'delivery_document')},
            },
        ),
    ]
