# Generated by Django 4.2.7 on 2026-09-08 13:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0017_migrate_ksef_links_data'),
        ('purchase_documents', '0006_migrate_pz_links_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItemPzLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_matched', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_line_links', to='delivery.deliveryitem')),
                ('invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pz_line_links', to='purchase_documents.purchasedocumentitem')),
            ],
            options={
                'verbose_name': 'Powiązanie pozycja faktury–pozycja PZ',
                'verbose_name_plural': 'Powiązania pozycje faktury–pozycje PZ',
                'ordering': ['created_at'],
                'unique_together': {('invoice_item', 'delivery_item')},
            },
        ),
    ]
