# Generated by Django 4.2.7 on 2026-09-15 10:57

from django.db import migrations, models


def force_par_no_vat(apps, schema_editor):
    PurchaseDocument = apps.get_model("purchase_documents", "PurchaseDocument")
    PurchaseDocument.objects.filter(doc_type="PAR").update(vat_deduction="none")


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_documents', '0007_add_invoiceitempzlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedocument',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Personal spend — no VAT deduction and not a business cost.'),
        ),
        migrations.AddField(
            model_name='purchasedocument',
            name='vat_deduction',
            field=models.CharField(choices=[('full', '100% — działalność'), ('half', '50% — samochód osobowy'), ('none', '0% — brak odliczenia')], default='full', help_text='VAT input share: 100%, 50% passenger car, or 0%. PAR without NIP is always 0%.', max_length=10),
        ),
        migrations.RunPython(force_par_no_vat, migrations.RunPython.noop),
    ]
