# Generated by Django 4.2.7 on 2026-08-29 15:41

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0021_ksef_optional_fields'),
        ('products', '0018_product_is_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalesReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('report_number', models.CharField(blank=True, max_length=32)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('saved', 'Zapisany')], default='draft', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Łączny przychód brutto (suma linii).', max_digits=12)),
                ('cost_total', models.DecimalField(blank=True, decimal_places=2, help_text='Łączny koszt własny (qty × avg_cost). Null jeśli brak kosztów.', max_digits=12, null=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('8.00'), help_text='Dominująca stawka VAT (dla prostych raportów kwotowych).', max_digits=5)),
                ('vat_included', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_reports', to='users.company')),
            ],
            options={
                'verbose_name': 'Daily Sales Report',
                'verbose_name_plural': 'Daily Sales Reports',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Czy ten szablon ładuje się automatycznie przy nowym raporcie.')),
                ('lines', models.JSONField(default=list, help_text='Lista linii: [{product_id, product_name, unit, qty, unit_price, unit_cost}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_report_templates', to='users.company')),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DailySalesReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('unit', models.CharField(default='szt.', max_length=20)),
                ('qty', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=4, help_text='Cena sprzedaży brutto per jednostka.', max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Koszt własny per jednostka (avg_cost snapshot).', max_digits=10, null=True)),
                ('line_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_report_lines', to='products.product')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales_reports.dailysalesreport')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
