# Generated by Django 4.2.7 on 2026-08-29 16:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalesreportitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('23.00'), help_text='Stawka VAT produktu (snapshot z momentu sprzedaży).', max_digits=5),
        ),
    ]
