# Generated by Django 4.2.7 on 2026-07-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_gv_member',
            field=models.BooleanField(default=False, help_text='Nabywca jest członkiem grupy VAT (GV). Rzadko stosowane.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_jst',
            field=models.BooleanField(default=False, help_text='Nabywca jest jednostką sektora finansów publicznych (JST). Zaznacz jeśli wystawiasz fakturę dla gminy/powiatu/szkoły itp.'),
        ),
    ]
