# Generated by Django 4.2.7 on 2026-04-23 11:14

from django.db import migrations, models
import django.db.models.deletion


def _ensure_company_for_user(apps, user_id):
    Company = apps.get_model("users", "Company")
    CompanyMembership = apps.get_model("users", "CompanyMembership")
    User = apps.get_model("users", "User")
    if user_id is None:
        co, _ = Company.objects.get_or_create(
            name="__legacy_no_user__",
            defaults={"is_active": True},
        )
        return co.pk
    user = User.objects.get(pk=user_id)
    m = CompanyMembership.objects.filter(user_id=user_id).first()
    if m:
        return m.company_id
    co = Company.objects.create(name=f"{user.username}'s organization", is_active=True)
    CompanyMembership.objects.create(
        user_id=user_id,
        company_id=co.pk,
        role="admin",
        is_active=True,
    )
    return co.pk


def backfill_customer_company(apps, schema_editor):
    Customer = apps.get_model("customers", "Customer")
    for row in Customer.objects.all():
        if row.company_id:
            continue
        row.company_id = _ensure_company_for_user(apps, row.user_id)
        row.save(update_fields=["company_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_current_company"),
        ("customers", "0002_alter_customer_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
        migrations.RunPython(backfill_customer_company, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="customer",
            index=models.Index(fields=["company"], name="idx_customers_company"),
        ),
    ]
