# Generated by Django 4.2.7 on 2026-09-21 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_ksef_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='podmiot3_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='podmiot3_country',
            field=models.CharField(blank=True, default='PL', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='podmiot3_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='podmiot3_nip',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='podmiot3_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='podmiot3_role',
            field=models.CharField(blank=True, choices=[('4', 'Faktor'), ('5', 'Odbiorca')], help_text='Rola trzeciej strony faktury FA-3: 4=Faktor, 5=Odbiorca. Puste = brak Podmiot3.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='podmiot3_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
