# Generated by Django 4.2.7 on 2026-09-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_podmiot3_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='podmiot3_id_wew',
            field=models.CharField(blank=True, help_text='Wewnętrzny identyfikator Podmiot3 (IDWew w FA-3), np. NIP-numer_sklepu.', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='podmiot3_role',
            field=models.CharField(blank=True, choices=[('2', 'Odbiorca'), ('4', 'Faktor')], help_text='Rola trzeciej strony faktury FA-3: 2=Odbiorca, 4=Faktor. Puste = brak Podmiot3.', max_length=2, null=True),
        ),
    ]
