# Generated by Django 4.2.7 on 2026-09-21 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_podmiot3_add_id_wew_fix_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='podmiot3_role',
            field=models.CharField(blank=True, choices=[('1', 'Faktor'), ('2', 'Odbiorca'), ('6', 'Dokonujący płatności'), ('11', 'Pracownik')], help_text='Rola trzeciej strony faktury FA-3: 1=Faktor, 2=Odbiorca, 6=Dokonujący płatności, 11=Pracownik.', max_length=2, null=True),
        ),
    ]
