# Generated by Django 4.2.7 on 2026-09-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_podmiot3_fix_role_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='podmiot3_role',
            field=models.CharField(blank=True, choices=[('1', 'Faktor'), ('2', 'Odbiorca'), ('3', 'Podmiot pierwotny'), ('4', 'Dodatkowy nabywca'), ('5', 'Wystawca faktury'), ('6', 'Dokonujący płatności'), ('11', 'Pracownik')], help_text='Rola trzeciej strony faktury FA-3: 1=Faktor, 2=Odbiorca, 3=Podmiot pierwotny, 4=Dodatkowy nabywca, 5=Wystawca faktury, 6=Dokonujący płatności, 11=Pracownik.', max_length=2, null=True),
        ),
    ]
