# Generated by Django 4.2.7 on 2026-10-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_podmiot3_add_roles_7_8_9_10'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='podmiot3_role_opis',
            field=models.CharField(blank=True, help_text="Opis roli podmiotu innego (OpisRoli w FA-3). Wymagany gdy podmiot3_role='12' (Rola inna).", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='podmiot3_role',
            field=models.CharField(blank=True, choices=[('1', 'Faktor'), ('2', 'Odbiorca'), ('3', 'Podmiot pierwotny'), ('4', 'Dodatkowy nabywca'), ('5', 'Wystawca faktury'), ('6', 'Dokonujący płatności'), ('7', 'JST – wystawca'), ('8', 'JST – odbiorca'), ('9', 'Członek GV – wystawca'), ('10', 'Członek GV – odbiorca'), ('11', 'Pracownik'), ('12', 'Rola inna')], help_text='Rola trzeciej strony faktury FA-3: 1=Faktor, 2=Odbiorca, 3=Podmiot pierwotny, 4=Dodatkowy nabywca, 5=Wystawca faktury, 6=Dokonujący płatności, 7=JST wystawca, 8=JST odbiorca, 9=GV wystawca, 10=GV odbiorca, 11=Pracownik.', max_length=2, null=True),
        ),
    ]
