# Generated by Django 4.2.7 on 2026-06-21 12:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('invoice_number', models.CharField(blank=True, help_text='Assigned on save, e.g. FV/2026/0001 (unique per company).', max_length=32, null=True)),
                ('issue_date', models.DateField()),
                ('sale_date', models.DateField()),
                ('due_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('transfer', 'Przelew'), ('cash', 'Gotówka'), ('card', 'Karta')], default='transfer', max_length=20)),
                ('subtotal_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('subtotal_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ksef_reference_number', models.CharField(blank=True, default='', max_length=255)),
                ('ksef_number', models.CharField(blank=True, default='', max_length=255)),
                ('ksef_status', models.CharField(choices=[('not_sent', 'Nie wysłana'), ('pending', 'Oczekuje'), ('sent', 'Wysłana'), ('accepted', 'Przyjęta'), ('rejected', 'Odrzucona')], default='not_sent', max_length=20)),
                ('ksef_sent_at', models.DateTimeField(blank=True, null=True)),
                ('ksef_error_message', models.TextField(blank=True, default='')),
                ('invoice_hash', models.CharField(blank=True, default='', max_length=255)),
                ('upo_received', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Wystawiona'), ('sent', 'Wysłana'), ('paid', 'Opłacona'), ('overdue', 'Przeterminowana'), ('cancelled', 'Anulowana')], default='draft', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('product_name', models.CharField(blank=True, default='', max_length=255)),
                ('product_unit', models.CharField(blank=True, default='', max_length=20)),
                ('pkwiu', models.CharField(blank=True, default='', max_length=32)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_net', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_vat', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('line_gross', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Invoice item',
                'verbose_name_plural': 'Invoice items',
                'ordering': ['created_at'],
            },
        ),
    ]
