# Generated by Django 4.2.7 on 2026-04-23 11:14

from django.db import migrations, models
import django.db.models.deletion


def backfill_invoice_company(apps, schema_editor):
    Invoice = apps.get_model("invoices", "Invoice")
    for row in Invoice.objects.all():
        if row.company_id:
            continue
        row.company_id = row.order.company_id
        row.save(update_fields=["company_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_current_company"),
        ("invoices", "0002_alter_invoice_options"),
        ("orders", "0002_add_company_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
        migrations.RunPython(backfill_invoice_company, migrations.RunPython.noop),
    ]
