# Generated by Django 4.2.7 on 2026-05-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_item'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'issued', 'sent', 'paid', 'overdue'])), fields=('company', 'order'), name='invoices_unique_active_invoice_per_order'),
        ),
    ]
