# Generated by Django 4.2.7 on 2026-06-23 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoices_unique_active_invoice_per_order',
        ),
        migrations.AddField(
            model_name='invoice',
            name='correction_reason',
            field=models.TextField(blank=True, default='', help_text='Required reason for FV-KOR.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='corrects_invoice',
            field=models.ForeignKey(blank=True, help_text='For FV-KOR: the original invoice this document corrects.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_correction',
            field=models.BooleanField(default=False, help_text='True for FV-KOR (correction invoice).'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_correction', False), ('status__in', ['draft', 'issued', 'sent', 'paid', 'overdue'])), fields=('company', 'order'), name='invoices_unique_active_non_correction_per_order'),
        ),
    ]
