# Generated by Django 4.2.7 on 2026-07-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoiceitem_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='annotation_fp',
            field=models.BooleanField(default=False, help_text='Faktura do paragonu z kasy fiskalnej (FP, P_106E_3, art. 109 ust. 3d ustawy VAT). Zaznacz gdy wystawiasz fakturę do wcześniej wydrukowanego paragonu.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='annotation_kasowa',
            field=models.BooleanField(default=False, help_text='Metoda kasowa (P_17, art. 21 ust. 1 ustawy VAT). Dotyczy podatników rozliczających VAT metodą kasową.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='annotation_marza',
            field=models.BooleanField(default=False, help_text='Procedura marży (P_23, art. 119 lub 120 ustawy VAT). Dotyczy biur podróży i handlu używanymi towarami.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='annotation_mpp',
            field=models.BooleanField(default=False, help_text='Mechanizm podzielonej płatności (MPP, P_16). Wymagany gdy faktura opiewa na ≥15 000 PLN i zawiera towary/usługi z załącznika nr 15 do ustawy VAT.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='annotation_odwrotne',
            field=models.BooleanField(default=False, help_text='Odwrotne obciążenie (P_18). Stosowane gdy VAT rozlicza nabywca (np. złom, odpady, usługi budowlane B2B).'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='annotation_oss',
            field=models.BooleanField(default=False, help_text='Procedura OSS — One Stop Shop (P_106E_1). Dotyczy sprzedaży B2C do konsumentów w innych krajach UE.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='annotation_tp',
            field=models.BooleanField(default=False, help_text='Powiązania między nabywcą a sprzedawcą (TP, P_106E_2). Wymagany zgodnie z §10 ust. 4 pkt 3 rozporządzenia JPK, gdy strony są podmiotami powiązanymi.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='annotation_trojstronna',
            field=models.BooleanField(default=False, help_text='Uproszczona procedura trójstronna (P_18A, art. 135 ust. 1 pkt 4 ustawy VAT). Dotyczy transakcji wewnątrzwspólnotowych z trzema podmiotami.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='annotation_zwolnienie',
            field=models.BooleanField(default=False, help_text='Dostawa zwolniona od podatku (P_19, art. 43 ust. 1, art. 113 ust. 1 i 9 lub art. 82 ust. 3). Zaznacz gdy sprzedajesz towary/usługi zwolnione z VAT.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_account_iban',
            field=models.CharField(blank=True, default='', help_text="Numer rachunku bankowego IBAN (np. PL12 1234 5678 9012 3456 7890 1234). Wymagany przy formie płatności 'przelew'.", max_length=34),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_name',
            field=models.CharField(blank=True, default='', help_text='Nazwa banku (opcjonalnie).', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='bank_swift',
            field=models.CharField(blank=True, default='', help_text='Kod SWIFT/BIC banku (opcjonalnie).', max_length=11),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_conditions',
            field=models.CharField(blank=True, default='', help_text='Warunki skonta — opis rabatu za wcześniejszą płatność (opcjonalnie, max 256 znaków).', max_length=256),
        ),
        migrations.AddField(
            model_name='invoice',
            name='extra_notes',
            field=models.TextField(blank=True, default='', help_text='Dodatkowy opis do faktury (widoczny na wydruku, nie wysyłany do KSeF).'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='footer_text',
            field=models.CharField(blank=True, default='', help_text='Stopka faktury — tekst drukowany u dołu faktury (opcjonalnie, max 3500 znaków).', max_length=3500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ksef_invoice_type',
            field=models.CharField(choices=[('VAT', 'Podstawowa (VAT)'), ('ZAL', 'Zaliczkowa (ZAL)'), ('ROZ', 'Rozliczeniowa (ROZ)')], default='VAT', help_text='Rodzaj faktury w KSeF FA-3. KOR jest ustawiany automatycznie.', max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ksef_payment_id',
            field=models.CharField(blank=True, default='', help_text='Identyfikator płatności KSeF (opcjonalnie, max 50 znaków).', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_link',
            field=models.CharField(blank=True, default='', help_text='Link do płatności bezgotówkowej (opcjonalnie, max 512 znaków).', max_length=512),
        ),
        migrations.AddField(
            model_name='invoice',
            name='prices_include_vat',
            field=models.BooleanField(default=True, help_text='True = faktura w cenach brutto (P_9B/P_11A). False = faktura w cenach netto (P_9A/P_11). Domyślnie True dla zgodności z istniejącymi fakturami.'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wz_numbers',
            field=models.JSONField(blank=True, default=list, help_text='Lista numerów dokumentów magazynowych WZ powiązanych z fakturą (opcjonalnie).'),
        ),
    ]
