# Generated by Django 4.2.7 on 2026-09-21 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
        ('invoices', '0010_ksef_optional_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Invoice order',
                'verbose_name_plural': 'Invoice orders',
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoices_unique_active_non_correction_per_order',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Primary order (legacy single-order invoices). Null for manual invoices.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.order'),
        ),
        migrations.AddField(
            model_name='invoiceorder',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_orders', to='invoices.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_orders', to='orders.order'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='orders',
            field=models.ManyToManyField(blank=True, help_text='All orders covered by this invoice (multi-order flow).', related_name='multi_invoices', through='invoices.InvoiceOrder', to='orders.order'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceorder',
            unique_together={('invoice', 'order')},
        ),
    ]
