# Generated by Django 4.2.7 on 2026-09-23 15:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_invoice_multi_order_and_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price_net',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
