# Generated by Django 4.2.7 on 2026-09-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_invoice_item_unit_price_net_4dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='place_of_issue',
            field=models.CharField(blank=True, default='', help_text='Miejsce wystawienia faktury (P_1M). Jeśli puste — używane jest miasto firmy.', max_length=100),
        ),
        migrations.AddField(
            model_name='invoice',
            name='show_wz_numbers',
            field=models.BooleanField(default=True, help_text='Czy wyświetlać numery dokumentów WZ na fakturze zbiorczej.'),
        ),
    ]
