# Generated by Django 4.2.7 on 2026-09-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_invoice_place_of_issue_show_wz'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sale_date_to',
            field=models.DateField(blank=True, help_text="Koniec okresu dla OkresFa (gdy sale_date_type='period').", null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sale_date_type',
            field=models.CharField(choices=[('single', 'Wspólna dla całej faktury data dokonania lub zakończenia dostawy towarów lub wykonania usługi'), ('period', 'Okres, którego dotyczy faktura (art. 19a ust. 3/4/5)'), ('issue', 'Data wystawienia jest taka sama jak data wykonania czynności'), ('various', 'Różne daty dla poszczególnych towarów lub usług')], default='single', help_text='Wariant pola P_6 w FA-3.', max_length=10),
        ),
    ]
