# Generated by Django 4.2.7 on 2026-10-01 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_invoice_sale_date_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Amount deducted from this ZAL on the ROZ. Null = full ZAL total_gross.', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roz_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advance_links', to='invoices.invoice')),
                ('zal_invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_links', to='invoices.invoice')),
            ],
            options={
                'verbose_name': 'Invoice advance link',
                'verbose_name_plural': 'Invoice advance links',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='invoiceadvance',
            constraint=models.UniqueConstraint(fields=('roz_invoice', 'zal_invoice'), name='invoices_advance_roz_zal_uniq'),
        ),
    ]
