# Generated by Django 4.2.7 on 2026-10-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_invoice_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_received_at',
            field=models.DateField(blank=True, help_text='Data otrzymania zapłaty (P_IZ / DataZaplaty w FA-3). Gdy ustawione → <P_IZ>1</P_IZ> + <DataZaplaty> w XML KSeF. Przy gotówce ustaw = data wystawienia. Zostaw puste dla przelewów.', null=True),
        ),
    ]
