# Generated by Django 4.2.7 on 2026-10-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_invoice_payment_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='other_payment_description',
            field=models.CharField(blank=True, default='', help_text="Opis innej formy płatności (InnyRodzajPlatnosci w FA-3). Wymagane gdy payment_method='other'.", max_length=256),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('transfer', 'Przelew bankowy'), ('cash', 'Gotówka'), ('card', 'Karta płatnicza'), ('voucher', 'Bon'), ('check', 'Czek'), ('credit', 'Kredyt'), ('mobile', 'Płatność mobilna'), ('other', 'Inna forma płatności')], default='transfer', max_length=20),
        ),
    ]
