# Generated by Django 4.2.7 on 2026-10-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0017_invoice_payment_methods_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='due_date_description',
            field=models.CharField(blank=True, default='', help_text="Opis terminu płatności (OpisTerminuPlatnosci w FA-3). Gdy ustawiony — zastępuje datę due_date w XML (<OpisTerminuPlatnosci> zamiast <Termin>). Np. 'Płatność przy odbiorze', 'Przelew w ciągu 7 dni od dostawy'.", max_length=256),
        ),
    ]
