# Generated by Django 4.2.7 on 2026-06-21 12:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KSeFProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seller_nip', models.CharField(max_length=20)),
                ('invoice_line_name', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KSeF product mapping',
                'verbose_name_plural': 'KSeF product mappings',
            },
        ),
        migrations.CreateModel(
            name='KSeFSentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reference_number', models.CharField(max_length=255, unique=True)),
                ('session_reference_number', models.CharField(max_length=255)),
                ('invoice_hash', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.CharField(blank=True, max_length=20)),
                ('shop', models.CharField(blank=True, max_length=255)),
                ('total_gross_cents', models.IntegerField(blank=True, null=True)),
                ('ksef_number', models.CharField(blank=True, max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=255)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('status_description', models.CharField(blank=True, max_length=512)),
                ('upo_xml', models.TextField(blank=True)),
                ('upo_hash', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KSeF sent invoice',
                'verbose_name_plural': 'KSeF sent invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KSeFSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_cookies_json', models.TextField(default='{}')),
                ('access_token_body', models.TextField(blank=True)),
                ('refresh_token_body', models.TextField(blank=True)),
                ('access_valid_until', models.DateTimeField(blank=True, null=True)),
                ('refresh_valid_until', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'KSeF session',
                'verbose_name_plural': 'KSeF sessions',
            },
        ),
        migrations.CreateModel(
            name='ReceivedKSeFInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ksef_number', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('invoicing_date', models.DateField(blank=True, null=True)),
                ('seller_nip', models.CharField(blank=True, max_length=20)),
                ('seller_name', models.CharField(blank=True, max_length=512)),
                ('buyer_nip', models.CharField(blank=True, max_length=20)),
                ('buyer_name', models.CharField(blank=True, max_length=512)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='PLN', max_length=10)),
                ('invoice_type', models.CharField(blank=True, max_length=50)),
                ('seller_address_l1', models.CharField(blank=True, max_length=512)),
                ('seller_address_l2', models.CharField(blank=True, max_length=512)),
                ('seller_country', models.CharField(blank=True, max_length=10)),
                ('xml_content', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, help_text='Payment due date, parsed from XML TerminyPlatnosci or set manually.', null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('opex_category', models.CharField(blank=True, choices=[('utilities', 'Media (prąd, gaz, woda)'), ('rent', 'Czynsz / leasing'), ('services', 'Usługi zewnętrzne'), ('transport', 'Transport / logistyka'), ('marketing', 'Marketing / reklama'), ('other', 'Inne')], help_text='Set to classify this invoice as an operating cost (OPEX) rather than a product purchase.', max_length=20, null=True)),
                ('opex_tagged_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Received KSeF invoice',
                'verbose_name_plural': 'Received KSeF invoices',
                'ordering': ['-issue_date', '-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivedKSeFInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_net_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('vat_rate', models.CharField(blank=True, max_length=10)),
                ('line_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ksef.receivedksefinvoice')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
