# Generated by Django 4.2.7 on 2026-06-21 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        ('ksef', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedksefinvoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ksef_invoices', to='users.company'),
        ),
        migrations.AddField(
            model_name='ksefsession',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ksef_session', to='users.company'),
        ),
        migrations.AddField(
            model_name='ksefsentinvoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksef_sent_invoices', to='users.company'),
        ),
        migrations.AddField(
            model_name='ksefproductmapping',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksef_product_mappings', to='users.company'),
        ),
        migrations.AddField(
            model_name='ksefproductmapping',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksef_mappings', to='products.product'),
        ),
        migrations.AlterUniqueTogether(
            name='receivedksefinvoice',
            unique_together={('company', 'ksef_number')},
        ),
        migrations.AlterUniqueTogether(
            name='ksefproductmapping',
            unique_together={('company', 'seller_nip', 'invoice_line_name')},
        ),
    ]
