# Generated by Django 4.2.1 on 2026-06-09 11:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_company_workflow_settings'),
        ('ksef', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedKSeFInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ksef_number', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('invoicing_date', models.DateField(blank=True, null=True)),
                ('seller_nip', models.CharField(blank=True, max_length=20)),
                ('seller_name', models.CharField(blank=True, max_length=512)),
                ('buyer_nip', models.CharField(blank=True, max_length=20)),
                ('buyer_name', models.CharField(blank=True, max_length=512)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('vat_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='PLN', max_length=10)),
                ('invoice_type', models.CharField(blank=True, max_length=50)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ksef_invoices', to='users.company')),
            ],
            options={
                'verbose_name': 'Received KSeF invoice',
                'verbose_name_plural': 'Received KSeF invoices',
                'ordering': ['-issue_date', '-first_seen_at'],
                'unique_together': {('company', 'ksef_number')},
            },
        ),
    ]
