# Generated by Django 4.2.7 on 2026-06-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksef', '0002_receivedksefinvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedKSeFInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=512)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit_net_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('vat_rate', models.CharField(blank=True, max_length=10)),
                ('line_net', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ksef.receivedksefinvoice')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
