# Generated by Django 4.2.7 on 2026-06-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksef', '0003_receivedksefinvoiceline'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedksefinvoice',
            name='seller_address_l1',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='receivedksefinvoice',
            name='seller_address_l2',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='receivedksefinvoice',
            name='seller_country',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='receivedksefinvoice',
            name='xml_content',
            field=models.TextField(blank=True),
        ),
    ]
