# Generated by Django 4.2.7 on 2026-06-10 09:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_company_workflow_settings'),
        ('products', '0012_translate_stock_movement_notes'),
        ('ksef', '0004_receivedksefinvoice_seller_address_l1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KSeFProductMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('seller_nip', models.CharField(max_length=20)),
                ('invoice_line_name', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksef_product_mappings', to='users.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksef_mappings', to='products.product')),
            ],
            options={
                'verbose_name': 'KSeF product mapping',
                'verbose_name_plural': 'KSeF product mappings',
                'unique_together': {('company', 'seller_nip', 'invoice_line_name')},
            },
        ),
    ]
