# Generated by Django 4.2.7 on 2026-06-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksef', '0006_supplier_payment_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedksefinvoice',
            name='opex_category',
            field=models.CharField(blank=True, choices=[('utilities', 'Media (prąd, gaz, woda)'), ('rent', 'Czynsz / leasing'), ('services', 'Usługi zewnętrzne'), ('transport', 'Transport / logistyka'), ('marketing', 'Marketing / reklama'), ('other', 'Inne')], help_text='Set to classify this invoice as an operating cost (OPEX) rather than a product purchase.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receivedksefinvoice',
            name='opex_tagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
