# Generated by Django 4.2.7 on 2026-09-15 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksef', '0012_alter_receivedksefinvoice_opex_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedksefinvoice',
            name='is_private',
            field=models.BooleanField(default=False, help_text='Personal spend — no VAT deduction and not a business cost.'),
        ),
        migrations.AddField(
            model_name='receivedksefinvoice',
            name='vat_deduction',
            field=models.CharField(choices=[('full', '100% — działalność'), ('half', '50% — samochód osobowy'), ('none', '0% — brak odliczenia')], default='full', help_text='VAT input share. Independent of opex_category (accountant labelling).', max_length=10),
        ),
    ]
