# Generated by Django 4.2.7 on 2026-05-26 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0004_add_zw_document_type'),
        ('orders', '0007_order_changelog'),
        ('products', '0011_add_product_pkwiu'),
        ('users', '0005_ksef_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VanRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Delivery date for this route.')),
                ('driver_name', models.CharField(blank=True, default='', max_length=255)),
                ('van_name', models.CharField(blank=True, default='', help_text='Human-readable van identifier (e.g. BIA 12345).', max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Zaplanowana'), ('loading', 'Załadunek'), ('in_progress', 'W trasie'), ('settling', 'Rozliczanie'), ('closed', 'Zamknięta')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='van_routes', to='users.company')),
                ('main_warehouse', models.ForeignKey(help_text='Main warehouse — source for the MM loading document.', on_delete=django.db.models.deletion.PROTECT, related_name='van_routes_as_main', to='products.warehouse')),
                ('mm_document', models.OneToOneField(blank=True, help_text='MM document created when the van is loaded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='van_route', to='delivery.deliverydocument')),
                ('orders', models.ManyToManyField(blank=True, help_text='Orders included as stops in this route.', related_name='van_routes', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='van_routes', to=settings.AUTH_USER_MODEL)),
                ('van_warehouse', models.ForeignKey(help_text='Mobile warehouse representing the van.', on_delete=django.db.models.deletion.PROTECT, related_name='van_routes_as_van', to='products.warehouse')),
            ],
            options={
                'verbose_name': 'Van route',
                'verbose_name_plural': 'Van routes',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
