# Generated by Django 4.2.7 on 2026-06-21 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        ('delivery', '0003_initial'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VanRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('route_number', models.CharField(blank=True, default='', help_text='Auto-generated route number, e.g. TR/2026/0001.', max_length=20)),
                ('date', models.DateField(help_text='Delivery date for this route.')),
                ('driver_name', models.CharField(blank=True, default='', max_length=255)),
                ('van_name', models.CharField(blank=True, default='', help_text='Human-readable van identifier (e.g. BIA 12345).', max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Zaplanowana'), ('loading', 'Załadunek'), ('in_progress', 'W trasie'), ('settling', 'Rozliczanie'), ('closed', 'Zamknięta')], default='planned', max_length=20)),
                ('reconciliation_summary', models.JSONField(blank=True, default=None, null=True)),
                ('carry_over_items', models.JSONField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='van_routes', to='users.company')),
                ('main_warehouse', models.ForeignKey(help_text='Main warehouse — source for the MM loading document.', on_delete=django.db.models.deletion.PROTECT, related_name='van_routes_as_main', to='products.warehouse')),
                ('mm_document', models.OneToOneField(blank=True, help_text='MM document created when the van is loaded.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loading_route', to='delivery.deliverydocument')),
                ('orders', models.ManyToManyField(blank=True, help_text='Orders included as stops in this route.', related_name='van_routes', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='van_routes', to=settings.AUTH_USER_MODEL)),
                ('van_warehouse', models.ForeignKey(help_text='Mobile warehouse representing the van.', on_delete=django.db.models.deletion.PROTECT, related_name='van_routes_as_van', to='products.warehouse')),
            ],
            options={
                'verbose_name': 'Van route',
                'verbose_name_plural': 'Van routes',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='vanroute',
            constraint=models.UniqueConstraint(condition=models.Q(('route_number__gt', '')), fields=('company', 'route_number'), name='van_route_company_route_number_uniq'),
        ),
    ]
