# Generated by Django 4.2.7 on 2026-05-31 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('van_routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanroute',
            name='reconciliation_summary',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
