# Generated by Django 4.2.7 on 2026-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('van_routes', '0003_alter_mm_document_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanroute',
            name='route_number',
            field=models.CharField(blank=True, default='', help_text='Auto-generated route number, e.g. TR/2026/0001.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='vanroute',
            constraint=models.UniqueConstraint(condition=models.Q(('route_number__gt', '')), fields=('company', 'route_number'), name='van_route_company_route_number_uniq'),
        ),
    ]
