# Generated by Django 4.2.7 on 2026-06-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('van_routes', '0004_add_route_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vanroute',
            name='carry_over_items',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
