# Generated by Django 4.2.7 on 2026-06-21 12:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='', max_length=20)),
                ('price_net', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_gross', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=23.0, max_digits=5)),
                ('sku', models.CharField(blank=True, max_length=50, null=True)),
                ('barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('pkwiu', models.CharField(blank=True, help_text='Polish product classification code', max_length=20)),
                ('track_batches', models.BooleanField(default=True)),
                ('min_stock_alert', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shelf_life_days', models.IntegerField(blank=True, null=True)),
                ('avg_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Weighted average purchase cost per unit, updated on each PZ receipt.', max_digits=10, null=True)),
                ('avg_cost_source', models.CharField(blank=True, choices=[('pz', 'Z PZ (przyjęcie)'), ('production', 'Z produkcji'), ('recipe', 'Szacunek z receptury'), ('manual', 'Ręcznie')], help_text='How avg_cost was last set: pz | production | recipe | manual.', max_length=20, null=True)),
                ('last_cost', models.DecimalField(blank=True, decimal_places=4, help_text='Unit cost from the most recent PZ receipt.', max_digits=10, null=True)),
                ('avg_cost_updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_resalable', models.BooleanField(default=True, help_text='If True, the product can be sold to customers (appears in invoice/order pickers).')),
                ('markup_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Target gross margin %. price_net is auto-suggested as avg_cost × (1 + markup/100).', max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity_available', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('received_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_initial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['received_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer'), ('damage', 'Damage'), ('reservation', 'Reservation'), ('unreservation', 'Unreservation')], default='adjustment', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Signed change applied to quantity_available.', max_digits=10)),
                ('quantity_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(help_text='Short code, e.g. MG, MV.', max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('warehouse_type', models.CharField(choices=[('main', 'Main'), ('mobile', 'Mobile'), ('customer', 'Customer'), ('external', 'External')], default='main', max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('fifo_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
