# Generated by Django 4.2.7 on 2026-06-21 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='products.warehouse'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product'),
        ),
        migrations.AddField(
            model_name='stockbatch',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.warehouse'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='products.warehouse'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['user'], name='idx_warehouses_user'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['company'], name='idx_warehouses_company'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['code'], name='idx_warehouses_code'),
        ),
        migrations.AddIndex(
            model_name='warehouse',
            index=models.Index(fields=['warehouse_type'], name='idx_warehouses_type'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['company'], name='idx_stock_movements_company'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product'], name='idx_stock_movements_product'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['warehouse'], name='idx_stock_movements_warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type'], name='idx_stock_movements_type'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['created_at'], name='idx_stock_movements_created'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['company'], name='idx_stock_batches_company'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['product'], name='idx_stock_batches_product'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['warehouse'], name='idx_stock_batches_warehouse'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['received_date'], name='idx_stock_batches_received'),
        ),
        migrations.AddIndex(
            model_name='stockbatch',
            index=models.Index(fields=['expiry_date'], name='idx_stock_batches_expiry'),
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['company'], name='idx_product_stock_company'),
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['product'], name='idx_product_stock_product'),
        ),
        migrations.AddIndex(
            model_name='productstock',
            index=models.Index(fields=['warehouse'], name='idx_product_stock_warehouse'),
        ),
        migrations.AddConstraint(
            model_name='productstock',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='uniq_productstock_product_warehouse'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['user'], name='idx_products_user'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company'], name='idx_products_company'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='idx_products_sku'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='idx_products_active'),
        ),
    ]
