# Generated by Django 4.2.7 on 2026-04-21 10:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_available', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_reserved', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stocks', to='products.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='idx_product_stock_product'), models.Index(fields=['warehouse'], name='idx_product_stock_warehouse')],
            },
        ),
        migrations.AddConstraint(
            model_name='productstock',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse'), name='uniq_productstock_product_warehouse'),
        ),
    ]
