# Generated by Django 4.2.7 on 2026-04-21 10:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(blank=True, max_length=50, null=True)),
                ('received_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('quantity_initial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_remaining', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.warehouse')),
            ],
            options={
                'ordering': ['received_date', 'id'],
                'indexes': [models.Index(fields=['product'], name='idx_stock_batches_product'), models.Index(fields=['warehouse'], name='idx_stock_batches_warehouse'), models.Index(fields=['received_date'], name='idx_stock_batches_received'), models.Index(fields=['expiry_date'], name='idx_stock_batches_expiry')],
            },
        ),
    ]
