# Generated by Django 4.2.7 on 2026-04-23 11:14

from django.db import migrations, models
import django.db.models.deletion


def _ensure_company_for_user(apps, user_id):
    Company = apps.get_model("users", "Company")
    CompanyMembership = apps.get_model("users", "CompanyMembership")
    User = apps.get_model("users", "User")
    if user_id is None:
        co, _ = Company.objects.get_or_create(
            name="__legacy_no_user__",
            defaults={"is_active": True},
        )
        return co.pk
    user = User.objects.get(pk=user_id)
    m = CompanyMembership.objects.filter(user_id=user_id).first()
    if m:
        return m.company_id
    co = Company.objects.create(name=f"{user.username}'s organization", is_active=True)
    CompanyMembership.objects.create(
        user_id=user_id,
        company_id=co.pk,
        role="admin",
        is_active=True,
    )
    return co.pk


def backfill_products_company(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    Warehouse = apps.get_model("products", "Warehouse")
    StockMovement = apps.get_model("products", "StockMovement")
    ProductStock = apps.get_model("products", "ProductStock")
    StockBatch = apps.get_model("products", "StockBatch")

    for row in Product.objects.all():
        if not row.company_id:
            row.company_id = _ensure_company_for_user(apps, row.user_id)
            row.save(update_fields=["company_id"])

    for row in Warehouse.objects.all():
        if not row.company_id:
            row.company_id = _ensure_company_for_user(apps, row.user_id)
            row.save(update_fields=["company_id"])

    for row in StockMovement.objects.all():
        if not row.company_id:
            row.company_id = _ensure_company_for_user(apps, row.user_id)
            row.save(update_fields=["company_id"])

    for row in ProductStock.objects.all():
        if not row.company_id:
            row.company_id = row.product.company_id
            row.save(update_fields=["company_id"])

    for row in StockBatch.objects.all():
        if not row.company_id:
            row.company_id = row.product.company_id
            row.save(update_fields=["company_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_current_company"),
        ("products", "0006_stockmovement"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
        migrations.AddField(
            model_name="productstock",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.company",
            ),
        ),
        migrations.RunPython(backfill_products_company, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["company"], name="idx_products_company"),
        ),
        migrations.AddIndex(
            model_name="productstock",
            index=models.Index(fields=["company"], name="idx_product_stock_company"),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(fields=["company"], name="idx_stock_batches_company"),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(fields=["company"], name="idx_stock_movements_company"),
        ),
        migrations.AddIndex(
            model_name="warehouse",
            index=models.Index(fields=["company"], name="idx_warehouses_company"),
        ),
    ]
