# Generated by Django 4.2.7 on 2026-04-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_stockmovement_unreservation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pkwiu',
            field=models.CharField(blank=True, help_text='Polish product classification code', max_length=20),
        ),
    ]
