# Generated by Django 4.2.7 on 2026-06-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_product_resalable'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avg_cost_source',
            field=models.CharField(blank=True, choices=[('pz', 'Z PZ (przyjęcie)'), ('production', 'Z produkcji'), ('recipe', 'Szacunek z receptury'), ('manual', 'Ręcznie')], help_text='How avg_cost was last set: pz | production | recipe | manual.', max_length=20, null=True),
        ),
    ]
