# Generated by Django 4.2.1 on 2026-06-20 14:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_company_fk_required'),
        ('users', '0009_track_supplier_payments'),
        ('products', '0015_avg_cost_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProductPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_net', models.DecimalField(decimal_places=2, help_text='Custom net price for this customer. Overrides product default.', max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_prices', to='customers.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_prices', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'customer'], name='idx_cpp_company_customer'), models.Index(fields=['company', 'product'], name='idx_cpp_company_product')],
                'unique_together': {('company', 'customer', 'product')},
            },
        ),
    ]
