# Generated by Django 4.2.7 on 2026-06-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_customer_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerproductprice',
            name='price_type',
            field=models.CharField(choices=[('net', 'Netto'), ('gross', 'Brutto')], default='net', help_text='Whether price_net stores a net or gross value.', max_length=5),
        ),
        migrations.AlterField(
            model_name='customerproductprice',
            name='price_net',
            field=models.DecimalField(decimal_places=2, help_text='Custom price value (interpretation depends on price_type).', max_digits=10),
        ),
    ]
